### ISSUE TITLE
Incorrect voltage for single phase inverter

### ISSUE THREAD

**Issue by petermdevries** [Gentleman1983/ginlong_solis_api_connector#3]
Just switching from the original ginlong-scraper to this one as the ginlong site isn't working for my anymore since the end of May.

I'm now sending output to PVO and notice that the Voltage is not correct for my system.
From the code I can see the voltage is now calculated as the averge of uAC1, uAC2 and uAC3. However I've a single phase inverter so uAC2 and uAC3 are 0 so as a result of this the voltage sent to PVO is incorrect. I just had a look at the API specs and seems that acOutputType defines whether the inverter is a single or 3-fase type.

> acOutputType AC output type 0: 1 phase Rest are 3 phase

So I think if acOutputType=0 uAC1 should be taken as Voltage and otherwise the average of uAC1..3 as currenlty implemented.

**Comment by Gentleman1983** [comment]
thx for the info. Had build the conversion for our 3 phase inverters. currently working on fix for that issue.

**Comment by petermdevries** [comment]
@Gentleman1983  Thanks for the quick update/fix. Unfortunetaly I see acOutputType is 1 for my inverter. Strange. 
Which value do you get for this field with a 3 phase inverter?

**Comment by TobiO79** [comment]
For our 3 phase inverters it is 1.
What model is your inverter?

**Comment by petermdevries** [comment]
It's a Solis 5G 1 phase inverter. I'll submit a ticket at Solis Cloud as it looks like it's wrong within their API.

**Comment by Gentleman1983** [comment]
Me is using a Solis 25kW 5G 3ph 3 MPPT - DC inverter and @TobiO79 an Solis 15kW 4G 3ph 2 MPPT - DC inverter. Both submit value `1` for the `acOutputType` property. Maybe I've got a look to add an override parameter for the single or multi phase mode. That should solve wrong values on Solis Cloud API.

**Comment by Gentleman1983** [comment]
@petermdevries have added issue #14 for providing an override. Hope to finish this today.

**Comment by petermdevries** [comment]
With the override it’s now working correctly. I also submitted a ticket to Solis about the acOutputType. I’ll let you know when I get an answer on that.
