### ISSUE TITLE
Use extended fields in PVO

### ISSUE THREAD

**Issue by petermdevries** [Gentleman1983/ginlong_solis_api_connector#4]
As I''ve donated to PVO, I can upload 6 additional parameters v7..v12. For my other inverter (a GoodWe) I'm using these extended parameters to send iPv1, uPv1, iPv2, uPv2 etc.

![image](https://github.com/Gentleman1983/ginlong_solis_api_connector/assets/15040708/4f4164ae-c6b8-4ea7-93be-de7dbf7c5310)

`        
# ExtendedData
payload['v7'] = vpv1
payload['v8'] = ipv1
payload['v10'] = vpv2
payload['v11'] = ipv2
`

Maybe it should be configurable via en ENV:

PVOUTPUT_EXTENDED_V7=iPv1
PVOUTPUT_EXTENDED_V8=uPv1
etc.

**Comment by petermdevries** [comment]
Thanks... working fine.

![image](https://github.com/Gentleman1983/ginlong_solis_api_connector/assets/15040708/0c4a6db5-fc3e-4948-8b18-ef717b42db16)

**Comment by Gentleman1983** [comment]
We are glad, that it works properly.
