### ISSUE TITLE
Device IDs when a battery is connected

### ISSUE THREAD

**Issue by ghost** [Gentleman1983/ginlong_solis_api_connector#40]
Hi

I used to use the old non-API version of this script. I have one inverter and one battery connected to that inverter. I used to run the old script twice, once with a 9 digit (ID) number that referred to the inverter and second time with a different 9 digit (ID) number for the battery.  The old URL endpoint would return two different sets of JSON. 

Each of these scripts then posted data into two separate InfluxDB buckets.  (I ran these scripts from March 2021 until the old URL endpoint stoped returning data a few weeks back. I found this API driven script a few days later.)

Using this new API driven version of the script I can see some battery related figures but they are all zero.  I can see my battery in the Solis app on my iPhone, so I know it works okay.

At the moment I simply cannot see how I get the data related to **my** battery from this script. I am not much a of coder, so I am probably doing something wrong.

Any thoughts on how I can pull the data from my battery? Perhaps I am looking at the wrong data points in InfluxDB!

Mark

**Comment by ghost** [comment]
It looks as if support needs to be added for the endpoint "/v1/api/stationDetail". As this contains information related to a battery.  Page 14 of the API guide.

**Comment by Gentleman1983** [comment]
Thanks. We'll have a look these days...

**Comment by Gentleman1983** [comment]
@all-contributors please add @MetPhoto for bug

**Comment by TobiO79** [comment]
Can you post a debug-Log from your installation, so we can see what battery-related fields are already in the data.

**Comment by TobiO79** [comment]
> It looks as if support needs to be added for the endpoint "/v1/api/stationDetail". As this contains information related to a battery. Page 14 of the API guide.

Page 14 connects to endpoint stationList. The values should also be in the inverterDetail endpoint...
Can you tell us, wich fields you need?

**Comment by TobiO79** [comment]
In reference to your debug-report under the wrong issue, the api transmitted, you have 2 inverters.
One inverter does not have batteries. The other one had values on battery-fields.
 
Use the script twice: one time with deviceid=0 and one time with deviceid=1

**Comment by TobiO79** [comment]
from your log:
{
"id": "1305435653845614593",
"name": "Battery inverter",
"batteryPower": 0.0,
"batteryPowerStr": "kW",
"batteryPowerPec": "1",
"batteryCapacitySoc": 100.0,
"parallelStatus": 0,
"parallelAddr": 0,
"parallelPhase": 0,
"parallelBattery": 0,
"batteryTodayChargeEnergy": 4.4,
"batteryTodayChargeEnergyStr": "kWh",
"batteryTotalChargeEnergy": 2.54,
"batteryTotalChargeEnergyStr": "MWh",
"batteryTodayDischargeEnergy": 1.0,
"batteryTodayDischargeEnergyStr": "kWh",
"batteryTotalDischargeEnergy": 1.306,
"batteryTotalDischargeEnergyStr": "MWh",
"batteryModel": 1,

**Comment by ghost** [comment]
Ah, I see. So the field in InfluxDB was picking up "batteryCapacitySoc" from the section before (which starts with a different ID) and that value is zero. But in the section you show above it shows 100(%).

I will do as you say, run the script a second time with device=1 and post to a separate InfluxDB bucket.

Thanks for your help.
Mark

**Comment by ghost** [comment]
Hmmm, with ID=1 I get

ERROR Your 'SOLIS_CLOUD_API_INVERTER_ID' (1) is larger than or equal to the available number of inverters (1). Please select a value between '0' and '0'
