### ISSUE TITLE
JSONDecode Error.  Bad Gateway.

### ISSUE THREAD

**Issue by philicibine** [Gentleman1983/ginlong_solis_api_connector#46]
I seem to be getting the following error quite alot.  
`ERROR https://www.soliscloud.com:13333/v1/api/inverterMonth -> 502: Bad Gateway`
`ERROR JSONDecodeError : Expecting value: line 1 column 1 (char 0)`

Also seeing the same for `https://www.soliscloud.com:13333/v1/api/inverterAll`

Is there anything I can do?  Or is it the api?

**Comment by ghost** [comment]
I have seen that quite often also. It seems to be intermittent.

**Comment by pmenzel2022** [comment]
best china reliable service. got this a lot, too.

**Comment by Gentleman1983** [comment]
Yeah, the rest web service has some issues with serving all users. It shows that the server is not able to serve information in time. I'll have some thoughts to handle this as it is almost occuring in normal service.
