### ISSUE TITLE
starting the Docker requires a username and password 

### ISSUE THREAD

**Issue by Stephen2615** [Gentleman1983/ginlong_solis_api_connector#51]
I am at a loss with this. I created an environment file and added the API etc. But when I start the docker, I get this error. 

ERROR Login failed for m.ginlong.com

I don't know why the Docker is trying to contact m.ginlong.com as I thought this was for soliscloud.com. 

If I don't try to put any username and password, I get this:

ERROR Username and password are mandatory for Ginlong Solis

So I tried putting in GINLONG_USER and GINLONG_PASSWORD and it spits out that above login failed.

I have used the API with my Home Assistant so I know its working. I want to use this with Grafana as my solar is complicated with three different PV systems.

Any help would be very appreciated.

Stephen

**Comment by Gentleman1983** [comment]
Hi @Stephen2615.

Sorry, we did not see the notification about this issue. Normally, the current containers should not communicate at anypoint with old ginlong api. Could you please provide information about the given environment configuration. Cross out your personal data. Do you use the most up-to-date release?

Yours

Christian

**Comment by Gentleman1983** [comment]
@all-contibutors please add @Stephen2615 for bug

**Comment by Gentleman1983** [comment]
@all-contributors please add @Stephen2615 for infrastructure, tests and code

**Comment by Gentleman1983** [comment]
@all-contributors please add @Stephen2615 for bug

**Comment by Stephen2615** [comment]
@Gentleman1983 

Thanks for the response. I have pulled the latest docker and installed in on a Debian host. 

sudo docker pull dkruyt/ginlong-scraper
[sudo] password for stephen:
Using default tag: latest
latest: Pulling from dkruyt/ginlong-scraper
Digest: sha256:f1120dc88e14d9e4675589ae7dbae7de549c10eb4d7b4f545737dbe1420a1b9e
Status: Image is up to date for dkruyt/ginlong-scraper:latest


PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

I am also running Home Assistant supervisor on this host and I have to run (AFAIK) docker with sudo.

The env file consists of:

LOG_LEVEL=DEBUG
GINLONG_USERNAME=xxx
GINLONG_PASSWORD=xxx

SOLIS_CLOUD_API_KEY_ID="xxx"
SOLIS_CLOUD_API_KEY_SECRET="xxx"
SOLIS_CLOUD_API_URL="https://www.soliscloud.com"
SOLIS_CLOUD_API_PORT="13333"
USE_INFLUX=yes

With the Ginlong details, I get this:
stephen@HomeAssistant:~/ginlong_solis_api_connector$ sudo  docker run --env-file ./env-file dkruyt/ginlong-scraper
2023-11-10 08:46:39,800 INFO Started ginlong-solis-scraper
2023-11-10 08:46:39,800 INFO Running job Every 5 minutes at 00:00:00 do main() (last run: [never], next run: 2023-11-10 08:51:00)
2023-11-10 08:46:39,802 DEBUG Starting new HTTPS connection (1): m.ginlong.com:443
2023-11-10 08:46:40,479 DEBUG https://m.ginlong.com:443 "POST /cpro/login/validateLogin.json HTTP/1.1" 302 242
2023-11-10 08:46:40,484 DEBUG Starting new HTTPS connection (1): www.soliscloud.com:443
2023-11-10 08:46:41,907 DEBUG https://www.soliscloud.com:443 "GET / HTTP/1.1" 200 None
2023-11-10 08:46:41,909 DEBUG Expecting value: line 1 column 1 (char 0)
2023-11-10 08:46:41,909 ERROR **Login failed for m.ginlong.com**
2023-11-10 08:46:41,913 INFO Next run is scheduled at 10/11/2023 08:51:00

If I comment out the Ginlong user info in the env file, I get:

 sudo  docker run --env-file ./env-file dkruyt/ginlong-scraper
2023-11-10 08:48:47,510 INFO Started ginlong-solis-scraper
2023-11-10 08:48:47,510 INFO Running job Every 5 minutes at 00:00:00 do main() (last run: [never], next run: 2023-11-10 08:53:00)
2023-11-10 08:48:47,510 **ERROR Username and password are mandatory for Ginlong Solis**
2023-11-10 08:48:47,510 INFO Next run is scheduled at 10/11/2023 08:53:00

As I mentioned when opening this, I can use the Solis API in Home Assistant and I get the data without any issues. 

Regards

Stephen

**Comment by Gentleman1983** [comment]
Okay, that is the reason. You pulled the original docker image. You have to build the current docker image using the given DOCKERFILE to receive the current docker image.

```
docker build -t Gentleman1983/ginlong-solis-api-connector -f ./Dockerfile .
```

**Comment by Stephen2615** [comment]
Thanks. That worked but I had to use a lowercase gentlemen1983. Now I have to figure out how to put the data into influxdb.

**Comment by Gentleman1983** [comment]
Great. Will have a look how to easily provide automated publishing to dockerhub or another provider for the images.
