### ISSUE TITLE
No MQTT output

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Gentleman1983/ginlong_solis_api_connector#70]
Hi, thanks for this API connector

I have configured MQTT but do not see the publish of any data .. please help
![image](https://github.com/Gentleman1983/ginlong_solis_api_connector/assets/2195190/42df7457-4ad9-4536-a52d-f2be5726a31d)

this is the log output i receive in my docker
![image](https://github.com/Gentleman1983/ginlong_solis_api_connector/assets/2195190/3ea25b43-dfa7-4126-ab7a-fa66455289b7)

thanks for your help

**Comment by TobiO79** [comment]
we will puplish a update today to fix some isues in the influx export.
in your case the script stopps in the influx-export and skips the mqtt-export. Please turn off influx until we publish the update.

**Comment by xX-Nexus-Xx** [comment]
thx a lot .. that worked fine
