### ISSUE TITLE
Syntax Error ==> Solis/pv/porwerPercent in MQTT

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Gentleman1983/ginlong_solis_api_connector#72]
There is a syntax error in MQTT output 

porwerPercent  ==> powerPercent

maybe this is in other areas as well (copy-paste)

**Comment by TobiO79** [comment]
The fieldname is just copied from the API. Ginglong Solis is using the misspelled fieldname.

Same "problem" in influxdb.

**Comment by xX-Nexus-Xx** [comment]
;) ok ..thx a lot
